### ISSUE TITLE
Image gets stuck

### ISSUE THREAD

**Issue by GarwelGarwel** [linuxgurugamer/KSPLoadingScreenManager#3]
After a dozen or two images change, one of them (always a different one, from screenshots folder in my case) gets stuck and is displayed until the end of the loading process. It does "blink", but appears again and again.

**Comment by linuxgurugamer** [comment]
Log file, please

**Comment by GarwelGarwel** [comment]
I just discovered the in-game configuration for this mod (the button was white before). Apparently, this is due to Total Slides being set to 20 and loading taking too long. Is the sliders num setting necessary? Why can't it just show all the files in the folder? Or does it have to load them permanently into memory or something?

**Comment by linuxgurugamer** [comment]
I need a log file.  Yes, sliders num is necessary, it does load things into memory

**Comment by linuxgurugamer** [comment]
Also, if you could turn on debugging, that would help

**Comment by GarwelGarwel** [comment]
[output_log.txt](https://github.com/linuxgurugamer/KSPLoadingScreenManager/files/1559789/output_log.txt)

**Comment by linuxgurugamer** [comment]
Thanks for the log file.  

I haven't seen this issue, I'll need to test this in my really big install, but I don't recall it happening in it.

How much memory does your system have (probably more than enough, but still)

**Comment by GarwelGarwel** [comment]
I have 16 GB, and it doesn't look like it's run out of RAM. I guess it'd CTD in that case.

What is the mod supposed to do after it's shown all the slides? Start over?

**Comment by linuxgurugamer** [comment]
If it runs out of memory, Windows will shut it down
It's a cycle, I'm not sure if it is random or sequential.

**Comment by linuxgurugamer** [comment]
Correction: When all slides are shown, it stops, I may change that to be a cycle.
How many images do you have in your screenshots folder?

It appears that you don't have a config specified.  Which means you didn't go in and set the debug flag.
From the log file:

File 'D:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/GameData/PluginData/LoadingScreenManager/LoadingScreenManager.cfg' does not 

Please go in, select debugging, close the window then get to the Space Center before exiting, then start up again, and if it still happens, send me the new log file.
Thanks

**Comment by GarwelGarwel** [comment]
Strange. I thought I'd set it. Maybe I didn't go to the Space Center then... Will try again.

I think playing the slideshow as a loop is a better solution than repeating one image. I have lots of screenshots in the folder, like 200+.

**Comment by yalov** [comment]
Still there. 
If the loading process take a longer time than showing a specified amount of images, it shows a last image again and again. 

> I think playing the slideshow as a loop is a better solution than repeating one image.

**Comment by linuxgurugamer** [comment]
Strange, my game loads in 7 minutes, and it doesn't loop like that.
Please make sure you are running the latest version, then send me the following:
output_log.exe
the config file(s) from LoadingScreenManager/PluginData

and a listing of the directory specified

**Comment by yalov** [comment]
https://www.dropbox.com/s/oehp9quf4ke0m40/LoadingScreenManager.cfg?dl=0
https://www.dropbox.com/s/usb2cbn2ifl705d/output_log.txt?dl=0
path = Screenshots/

**Comment by linuxgurugamer** [comment]
How many files are in your Screenshots directory?
Can you get me a detailed list, please

**Comment by yalov** [comment]
134 + 1 folder (ignored)
https://www.dropbox.com/s/t2b1411xw31x6bn/content%20of%20scr.txt?dl=0

**Comment by linuxgurugamer** [comment]
This shoould have been solved in the latest reelase, please check and reopen if necessary

**Comment by GarwelGarwel** [comment]
Unfortunately, the issue is still present. One of the screenshots repeats infinitely (i.e. till the game loads).

**Comment by linuxgurugamer** [comment]
Do you have it set to adjust the time after each load? 
If so, have you loaded and exited normally, and then try loading again?

The actual showing of the images is internal to KSP

**Comment by GarwelGarwel** [comment]
After some more tests, it seems to work ok. I don't know what was wrong in the first try, but I'm closing the issue.
